name: Mike build and deploy

on:
  push:
    branches:
      - main
      - auto-deploy-main

jobs:
  build:
    runs-on: ubuntu-latest
    name: mike deploy main on gh-pages
    steps:
      - name: git-checkout
        uses: actions/checkout@v2
        with:
          ref: main
          fetch-depth: 0
          token: ${{ secrets.MIKE_PAT }}

      - name: Set up Python 3.x
        uses: actions/setup-python@v1
        with:
          python-version: '3.x'
          architecture: 'x64'

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"
 
      - name: Install dependencies
        run: |
          cd $GITHUB_WORKSPACE 
          pip install -r requirements.txt

      - name: Configure Git user
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Build and deploy
        run: |
          cd $GITHUB_WORKSPACE
          mike deploy --push git-main
